### ISSUE TITLE
Postfix | Dovecot is configured to use the LDAP super admin account

### ISSUE THREAD

**Issue by tharindu99** [LSFLK/Copper#168]
Security Issue: Postfix is configured to use the LDAP super admin account to access mail related parameters which creates a security risk. A low privileged account should be configured and used in postfix in accessing LDAP parameters.

**Comment by tharangar** [comment]
This issue was sorted by 
1. Creating ldap admin user with readonly privileges.
2. Configure readonly user in postfix and dovecot configurations.
3. Let customers to select username password for ldap readonly user.
4. Create a import file for ldap server with two demo users and domain name.
