### ISSUE TITLE
Copper Hub - Alerting and Monitoring : generic agent model.

### ISSUE THREAD

**Issue by anuudb** [LSFLK/Copper#60]
sub tasks : 
- integrate suitable model with the core, for alerting management purposes. 
- testing alerting & monitoring process 
- connect with slack/email or any related communication method.

**Comment by tharangar** [comment]
Prometheus and alert Manager deployed with k8s as initial step. Now we have customize both of those deployments according to our plan.

**Comment by anuudb** [comment]
Solved with v0.6.0
