### ISSUE TITLE
Mail archiving, backup and recovery

### ISSUE THREAD

**Issue by anuudb** [LSFLK/Copper#61]
Mail archiving and backup are very important aspects of a mail server. And also the recovery part. We are planing to get them to the production level by getting support of k8s volumes. 
https://kubernetes.io/docs/concepts/storage/volumes/

**Comment by tharangar** [comment]
Mail backup and Restore achived using hostpath volume configuration in kubernetes.
All processes followed to achieve this and testing procedures has been documented in following url.

http://copperdoc.opensource.lk/Backups/
