### ISSUE TITLE
Implement Generic Agent

### ISSUE THREAD

**Issue by tharindu99** [LSFLK/Copper#79]
Initial design for generic agent model.

**Comment by tharangar** [comment]
Even Kubernetes has mentioned about prometheus in their monitoring references.
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/

**Comment by tharangar** [comment]
Tested using filebeat as a generic agent model.

**Comment by anuudb** [comment]
Completed
